[package]
name = "tacview-splitter"
version = "0.3.1"
authors = ["132nd-Professor <132nd-Professor>"]
edition = "2021"

[dependencies]
zip = {version = ">= 0.6.2", default-features = false, features = ["deflate"]}

[profile.release]
lto = true
opt-level = 3
strip = "symbols"
